### ISSUE TITLE
Error: "invalid syntax"

### ISSUE THREAD

**Issue by amandafrench** [wcaleb/omekadd#3]
Hi Caleb -- I get the error  

```
File "./omekacsv.py", line 80
c.writerow({k:v.encode('utf-8', 'replace') for k,v in D.items() if isinstance(v, unicode)})
                                             ^
```

SyntaxError: invalid syntax`

when I run omekacsv.py. I'm running Python 2.6.6. and PHP 5.3.x on a shared Linux box.

**Comment by wcaleb** [comment]
@amandafrench That line uses a dictionary comprehension, which is only available in Python 2.7. But there should be [a way around the problem](http://stackoverflow.com/questions/1747817/python-create-a-dictionary-with-list-comprehension).

Try changing the line to:

```
 c.writerow(dict((k, v.encode('utf-8', 'replace')) for (k,v) in D.items() if isinstance(v, unicode)))
```

and let me know if that seems to work.

**Comment by amandafrench** [comment]
Thanks, @wcaleb. I get a new error message now: 

```
Traceback (most recent call last):
File "./omekacsv.py", line 3, in <module>
from omekaclient import OmekaClient
File "/home3/alfrench/public_html/steepletoplibrary.org/omekadd/omekaclient.py", line 1, in <module>
import httplib2
ImportError: No module named httplib2
```

I did manage to export the data using @patrickmj's [https://github.com/patrickmj/OmekaApiToCsv](OmekaApiToCsv), by the way, so no worries if you just want to close the issue and say that the script requires Python 2.7.

**Comment by wcaleb** [comment]
This one might be easier to solve if you can install Python modules. Do 
you have pip? Then you could use that to get the module.

http://stackoverflow.com/a/6468823/1848454

Might need to add a "sudo" in front of the pip command.

**Comment by amandafrench** [comment]
My shared server on HostGator won't let me install it myself (the box has httplib but not httplib2), but I've submitted a ticket. Thanks!

**Comment by wcaleb** [comment]
@amandafrench Just going through old issues and wondered if you ever managed to get this to work?

**Comment by amandafrench** [comment]
Nope -- httplib2 wasn't available on my shared host. Thanks for checking back.
